export const sqlGetAllTableNamesCurrentUserHasRights = `SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE 
    FROM INFORMATION_SCHEMA.TABLES 
    WHERE
        TABLE_TYPE = 'BASE TABLE' AND
        HAS_PERMS_BY_NAME (QUOTENAME(TABLE_SCHEMA)+'.'+QUOTENAME(TABLE_NAME), 'OBJECT', 'SELECT') &
        HAS_PERMS_BY_NAME (QUOTENAME(TABLE_SCHEMA)+'.'+QUOTENAME(TABLE_NAME), 'OBJECT', 'INSERT') &
        HAS_PERMS_BY_NAME (QUOTENAME(TABLE_SCHEMA)+'.'+QUOTENAME(TABLE_NAME), 'OBJECT', 'UPDATE') = 1
    ORDER BY TABLE_NAME ASC;
`;

export const sqlUserIsServerAdmin = `SELECT HAS_PERMS_BY_NAME(NULL, NULL, 'CREATE LOGIN');`;

export const sqlUserIsDbo = `SELECT HAS_PERMS_BY_NAME(NULL, 'DATABASE', 'CREATE USER');`;

export const sqlGetColumnInformationForSchemaAndTable = `SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME,
    ORDINAL_POSITION, COLUMN_DEFAULT, IS_NULLABLE, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, CHARACTER_OCTET_LENGTH,
    NUMERIC_PRECISION, NUMERIC_PRECISION_RADIX, NUMERIC_SCALE, DATETIME_PRECISION, CHARACTER_SET_CATALOG, CHARACTER_SET_SCHEMA,
    CHARACTER_SET_NAME, COLLATION_CATALOG, COLLATION_SCHEMA, COLLATION_NAME, DOMAIN_CATALOG, DOMAIN_SCHEMA, DOMAIN_NAME
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = @Table_Schema AND
        TABLE_NAME = @Table_Name
    ORDER BY TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION ASC;
`;
