export const sqlGetAllTableNamesCurrentUserHasRights = `SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE 
    FROM information_schema.Tables 
    WHERE
        TABLE_TYPE = 'BASE TABLE' AND
        HAS_PERMS_BY_NAME (QUOTENAME(TABLE_SCHEMA)+'.'+QUOTENAME(TABLE_NAME), 'OBJECT', 'SELECT') &
        HAS_PERMS_BY_NAME (QUOTENAME(TABLE_SCHEMA)+'.'+QUOTENAME(TABLE_NAME), 'OBJECT', 'INSERT') &
        HAS_PERMS_BY_NAME (QUOTENAME(TABLE_SCHEMA)+'.'+QUOTENAME(TABLE_NAME), 'OBJECT', 'UPDATE') = 1
    order by TABLE_NAME;
`;

export const sqlUserIsServerAdmin = `SELECT HAS_PERMS_BY_NAME(NULL, NULL, 'CREATE LOGIN');`;

export const sqlUserIsDbo = `SELECT HAS_PERMS_BY_NAME(NULL, 'DATABASE', 'CREATE USER');`;
