-- find all tables the current user is responsible for
select TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE 
	from information_schema.Tables 
	where
		TABLE_TYPE = 'BASE TABLE' and
		HAS_PERMS_BY_NAME (QUOTENAME(TABLE_SCHEMA)+'.'+QUOTENAME(TABLE_NAME), 'OBJECT', 'SELECT') &
		HAS_PERMS_BY_NAME (QUOTENAME(TABLE_SCHEMA)+'.'+QUOTENAME(TABLE_NAME), 'OBJECT', 'INSERT') &
		HAS_PERMS_BY_NAME (QUOTENAME(TABLE_SCHEMA)+'.'+QUOTENAME(TABLE_NAME), 'OBJECT', 'UPDATE') = 1
	order by TABLE_NAME;

